In [2]:
data_path = "D:\\Machine-Learning Course\\uDemy\\ML\\Part 1 - Data Preprocessing\\Python\\Data.csv"

In [3]:
!pip install pandas

In [23]:
import pandas as pd
dataframe = pd.read_csv(data_path)
dataframe2 = pd.read_csv(data_path)

In [6]:
print(dataframe.values)

[['France' 44.0 72000.0 'No']
 ['Spain' 27.0 48000.0 'Yes']
 ['Germany' 30.0 54000.0 'No']
 ['Spain' 38.0 61000.0 'No']
 ['Germany' 40.0 nan 'Yes']
 ['France' 35.0 58000.0 'Yes']
 ['Spain' nan 52000.0 'No']
 ['France' 48.0 79000.0 'Yes']
 ['Germany' 50.0 83000.0 'No']
 ['France' 37.0 67000.0 'Yes']]


In [7]:
!pip install sklearn

  Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=1320 sha256=31a9bf917f1620468b165fd5679bbe9bb146d862a42784f3f370398b00cb6e44
  Stored in directory: c:\users\soumya\appdata\local\pip\cache\wheels\46\ef\c3\157e41f5ee1372d1be90b09f74f82b10e391eaacca8f22d33e
Successfully built sklearn


In [13]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imputer.fit(x[:, 1:3])
x[:,1:3] = imputer.transfor(x[:,1:3])

NameError: name 'x' is not defined

In [9]:
!pip install numpy

In [10]:
import numpy as np

In [21]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imputer.fit(x[:, 1:3])
x[:,1:3] = imputer.transform(x[:,1:3])

In [18]:
x = dataframe.iloc[:, :-1].values
y = dataframe.iloc[:, -1].values

In [19]:
print(x)
print(y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [22]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [27]:
print(dataframe2.values)

[['France' 44.0 72000.0 'No']
 ['Spain' 27.0 48000.0 'Yes']
 ['Germany' 30.0 54000.0 'No']
 ['Spain' 38.0 61000.0 'No']
 ['Germany' 40.0 nan 'Yes']
 ['France' 35.0 58000.0 'Yes']
 ['Spain' nan 52000.0 'No']
 ['France' 48.0 79000.0 'Yes']
 ['Germany' 50.0 83000.0 'No']
 ['France' 37.0 67000.0 'Yes']]


In [28]:
dataframe2 = dataframe2.fillna(dataframe2.mean())

In [29]:
print(dataframe2)

   Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes


In [31]:
df = pd.get_dummies(dataframe.Country, prefix = 'Country')
print(df)

   Country_France  Country_Germany  Country_Spain
0               1                0              0
1               0                0              1
2               0                1              0
3               0                0              1
4               0                1              0
5               1                0              0
6               0                0              1
7               1                0              0
8               0                1              0
9               1                0              0


In [40]:
df['Purchased'] = dataframe2['Purchased']

In [45]:
df.values

array([[1, 0, 0, 44.0, 72000.0, 'No'],
       [0, 0, 1, 27.0, 48000.0, 'Yes'],
       [0, 1, 0, 30.0, 54000.0, 'No'],
       [0, 0, 1, 38.0, 61000.0, 'No'],
       [0, 1, 0, 40.0, 63777.77777777778, 'Yes'],
       [1, 0, 0, 35.0, 58000.0, 'Yes'],
       [0, 0, 1, 38.77777777777778, 52000.0, 'No'],
       [1, 0, 0, 48.0, 79000.0, 'Yes'],
       [0, 1, 0, 50.0, 83000.0, 'No'],
       [1, 0, 0, 37.0, 67000.0, 'Yes']], dtype=object)

In [43]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [0])], remainder = 'passthrough')
df2 = np.array(ct.fit_transform(dataframe))

In [44]:
df2

array([[1.0, 0.0, 0.0, 44.0, 72000.0, 'No'],
       [0.0, 0.0, 1.0, 27.0, 48000.0, 'Yes'],
       [0.0, 1.0, 0.0, 30.0, 54000.0, 'No'],
       [0.0, 0.0, 1.0, 38.0, 61000.0, 'No'],
       [0.0, 1.0, 0.0, 40.0, nan, 'Yes'],
       [1.0, 0.0, 0.0, 35.0, 58000.0, 'Yes'],
       [0.0, 0.0, 1.0, nan, 52000.0, 'No'],
       [1.0, 0.0, 0.0, 48.0, 79000.0, 'Yes'],
       [0.0, 1.0, 0.0, 50.0, 83000.0, 'No'],
       [1.0, 0.0, 0.0, 37.0, 67000.0, 'Yes']], dtype=object)

In [46]:
from sklearn.preprocessing import LabelEncoder

In [47]:
le = LabelEncoder()
df['Purchased'] = le.fit_transform(df['Purchased'])

In [48]:
df

Country_France  Country_Germany  Country_Spain        Age        Salary  \
0               1                0              0  44.000000  72000.000000   
1               0                0              1  27.000000  48000.000000   
2               0                1              0  30.000000  54000.000000   
3               0                0              1  38.000000  61000.000000   
4               0                1              0  40.000000  63777.777778   
5               1                0              0  35.000000  58000.000000   
6               0                0              1  38.777778  52000.000000   
7               1                0              0  48.000000  79000.000000   
8               0                1              0  50.000000  83000.000000   
9               1                0              0  37.000000  67000.000000   

   Purchased  
0          0  
1          1  
2          0  
3          0  
4          1  
5          1  
6          0  
7          1  
8          0  
9          1

In [58]:
X = df.iloc[:, : -1]

In [59]:
Y = df.iloc[:, -1]

In [60]:
print(X)
print(Y)

   Country_France  Country_Germany  Country_Spain        Age        Salary
0               1                0              0  44.000000  72000.000000
1               0                0              1  27.000000  48000.000000
2               0                1              0  30.000000  54000.000000
3               0                0              1  38.000000  61000.000000
4               0                1              0  40.000000  63777.777778
5               1                0              0  35.000000  58000.000000
6               0                0              1  38.777778  52000.000000
7               1                0              0  48.000000  79000.000000
8               0                1              0  50.000000  83000.000000
9               1                0              0  37.000000  67000.000000
0    0
1    1
2    0
3    0
4    1
5    1
6    0
7    1
8    0
9    1
Name: Purchased, dtype: int32


In [61]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 1)

In [68]:
X_train.values

array([[0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.87777778e+01,
        5.20000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.00000000e+01,
        6.37777778e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.40000000e+01,
        7.20000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.80000000e+01,
        6.10000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 2.70000000e+01,
        4.80000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.80000000e+01,
        7.90000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 5.00000000e+01,
        8.30000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.50000000e+01,
        5.80000000e+04]])

In [66]:
X1_train

array([[0.0, 0.0, 1.0, nan, 52000.0],
       [0.0, 1.0, 0.0, 40.0, nan],
       [1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0]], dtype=object)

In [63]:
X1= df2[:, :-1]

In [64]:
Y1 = df2[:, -1]

In [65]:
X1_train, X1_test, Y1_train, Y1_test = train_test_split(X1, Y1, test_size = .2, random_state = 1)